"""init

Revision ID: 84cfa967d10a
Revises: 
Create Date: 2024-04-11 20:31:03.913075

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '84cfa967d10a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_info',
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('landmark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_info_area'), 'address_info', ['area'], unique=False)
    op.create_index(op.f('ix_address_info_city'), 'address_info', ['city'], unique=False)
    op.create_index(op.f('ix_address_info_country'), 'address_info', ['country'], unique=False)
    op.create_index(op.f('ix_address_info_created_on'), 'address_info', ['created_on'], unique=False)
    op.create_index(op.f('ix_address_info_id'), 'address_info', ['id'], unique=False)
    op.create_index(op.f('ix_address_info_is_active'), 'address_info', ['is_active'], unique=False)
    op.create_index(op.f('ix_address_info_landmark'), 'address_info', ['landmark'], unique=False)
    op.create_index(op.f('ix_address_info_latitude'), 'address_info', ['latitude'], unique=False)
    op.create_index(op.f('ix_address_info_longitude'), 'address_info', ['longitude'], unique=False)
    op.create_index(op.f('ix_address_info_pincode'), 'address_info', ['pincode'], unique=False)
    op.create_index(op.f('ix_address_info_state'), 'address_info', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_info_state'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_pincode'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_longitude'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_latitude'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_landmark'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_is_active'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_id'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_created_on'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_country'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_city'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_area'), table_name='address_info')
    op.drop_table('address_info')
    # ### end Alembic commands ###
